const test = require('node:test')
const assert = require('node:assert')
const {
  createEmptyState,
  validateState,
  sealState,
  stateHash,
  evaluateFreshness,
  renderMarkdown,
} = require('../lib/cognition-core/index.js')

const populatedState = () => {
  const state = createEmptyState()
  state.mission = {
    purpose: 'Preserve evidence-backed project intent across coding sessions.',
    intended_users: ['maintainers'],
    use_cases: ['architecture-aware coding'],
    environment: ['DSH'],
  }
  state.architecture = { components: ['Cognition Core', 'Goal Governor'], boundaries: ['Core never executes project commands'] }
  state.evidence.push({ id: 'E1', kind: 'benchmark', ref: 'evaluation/results.json', fingerprint: 'abc' })
  state.value_claims.push({
    id: 'V1', statement: 'A goal governor can reduce extra edits.', authority: 'model_inferred',
    proof_status: 'hypothesis', scope: 'DSH pilot', confidence: 0.5, evidence_refs: ['E1'],
    invalidation_conditions: ['Controlled trial shows no improvement'], freshness: { status: 'fresh', fingerprint: 'abc' },
  })
  state.invariants.push({
    id: 'I1', statement: 'Researcher remains read-only.', lifecycle: 'ratified', strength: 'hard',
    authority: 'owner_ratified', evidence_refs: ['E1'], change_policy: 'Owner must approve a new cognition revision.',
  })
  state.decisions.push({
    id: 'D1', statement: 'JSON is canonical.', rationale: 'Avoid dual-write drift.', status: 'active',
    authority: 'owner_ratified', evidence_refs: ['E1'],
  })
  state.known_unknowns.push({ id: 'U1', statement: 'Cross-client value is unknown.', evidence_refs: [] })
  state.next_proofs.push({ id: 'P1', statement: 'Run the four-arm DSH experiment.', evidence_refs: ['E1'] })
  return state
}

test('cognition state seals deterministically and detects tampering', () => {
  const sealed = sealState(populatedState())
  assert.equal(sealed.state_hash, stateHash(sealed))
  assert.deepEqual(sealState(populatedState()), sealed)
  sealed.mission.purpose = 'tampered'
  assert.throws(() => validateState(sealed), /does not match canonical state content/)
})

test('ratified invariants require owner authority and evidence refs must resolve', () => {
  const wrongAuthority = populatedState()
  wrongAuthority.invariants[0].authority = 'model_inferred'
  assert.throws(() => validateState(wrongAuthority), /owner_ratified/)

  const unknownEvidence = populatedState()
  unknownEvidence.value_claims[0].evidence_refs = ['missing']
  assert.throws(() => validateState(unknownEvidence), /unknown evidence/)
})

test('freshness reports evidence and dependent claims without mutating state', () => {
  const state = sealState(populatedState())
  const before = JSON.stringify(state)
  const report = evaluateFreshness(state, { E1: 'changed' })
  assert.deepEqual(report.stale_evidence, ['E1'])
  assert.deepEqual(report.stale_claims, ['V1'])
  assert.equal(JSON.stringify(state), before)
})

test('markdown is a deterministic generated projection', () => {
  const state = sealState(populatedState())
  const first = renderMarkdown(state)
  const second = renderMarkdown(state)
  assert.equal(first, second)
  assert.match(first, /GENERATED by project-cognition/)
  assert.match(first, /Researcher remains read-only/)
  assert.match(first, /Cross-client value is unknown/)
})
